function buildResource<T extends string>(resource: T) {
  return {
    LIST: `${resource}.list`,
    CREATE: `${resource}.create`,
    UPDATE: `${resource}.update`,
    TOGGLE_ACTIVE: `${resource}.toggle-active`,
    SOFT_DELETE: `${resource}.soft-delete`,
    HARD_DELETE: `${resource}.hard-delete`,
    RESTORE: `${resource}.restore`,
  } as const;
}

export const PERMISSIONS = {
  USERS: {
    LIST: 'users.list',
    CREATE: 'users.create',
    UPDATE: 'users.update',
    CHANGE_PASSWORD: 'users.change-password',
    TOGGLE_ACTIVE: 'users.toggle-active',
    SOFT_DELETE: 'users.soft-delete',
    HARD_DELETE: 'users.hard-delete',
    RESTORE: 'users.restore',
  },
  ROLES: {
    LIST: 'roles.list',
    CREATE: 'roles.create',
    UPDATE: 'roles.update',
    TOGGLE_ACTIVE: 'roles.toggle-active',
    SOFT_DELETE: 'roles.soft-delete',
    HARD_DELETE: 'roles.hard-delete',
    RESTORE: 'roles.restore',
    ASSIGN_PERMISSIONS: 'roles.assign-permissions',
  },
  PERMISSIONS: {
    LIST: 'permissions.list',
  },
  SPECIALTIES: buildResource('specialties'),
  PATIENTS: buildResource('patients'),
  DOCTORS: buildResource('doctors'),
  CARE_CENTERS: buildResource('care-centers'),
  INSURANCES: buildResource('insurances'),
  PATHOLOGIES: buildResource('pathologies'),
  SERVICE_TYPES: buildResource('service-types'),
  CONTRACTORS: buildResource('contractors'),
  EXCHANGE_RATES: buildResource('exchange-rates'),
  BRANCHES: buildResource('branches'),
  TAX_UNITS: buildResource('tax-units'),
  ORDERS: {
    LIST: 'orders.list',
    CREATE: 'orders.create',
    UPDATE: 'orders.update',
    SOFT_DELETE: 'orders.soft-delete',
    HARD_DELETE: 'orders.hard-delete',
    RESTORE: 'orders.restore',
    STAGE_ATTENTION: 'orders.stage-attention',
    STAGE_REPORT: 'orders.stage-report',
    STAGE_BILLING: 'orders.stage-billing',
    EDIT_AMOUNT: 'orders.edit-amount',
    SET_PROVIDER_AMOUNT: 'orders.set-provider-amount',
  },
  ACCOUNTS_PAYABLE: {
    LIST: 'accounts-payable.list',
    UPDATE: 'accounts-payable.update',
  },
  ACCOUNTS_RECEIVABLE: {
    LIST: 'accounts-receivable.list',
    UPDATE: 'accounts-receivable.update',
  },
  TAXES_PAYABLE: {
    LIST: 'taxes-payable.list',
    UPDATE: 'taxes-payable.update',
  },
  APP_CONFIG: {
    VIEW: 'app-config.view',
    UPDATE: 'app-config.update',
  },
  REPORTS: {
    RECEIVABLES_LIST: 'reports.receivables.list',
    PAYABLES_LIST: 'reports.payables.list',
    FINANCIAL_SUMMARY_LIST: 'reports.financial-summary.list',
    DOCTOR_PRODUCTION_LIST: 'reports.doctor-production.list',
    INSURANCE_PRODUCTION_LIST: 'reports.insurance-production.list',
    AGING_LIST: 'reports.aging.list',
    COLLECTIONS_LIST: 'reports.collections.list',
    DISBURSEMENTS_LIST: 'reports.disbursements.list',
    ORDERS_TRACKING_LIST: 'reports.orders-tracking.list',
    SERVICES_BILLED_LIST: 'reports.services-billed.list',
    TAXES_RETAINED_LIST: 'reports.taxes-retained.list',
    EXECUTIVE_PANEL_LIST: 'reports.executive-panel.list',
    ORDERS_ANALYTICS_LIST: 'reports.orders-analytics.list',
    INSURER_COLLECTIONS_LIST: 'reports.insurer-collections.list',
  },
} as const;
